### ISSUE TITLE
transmitter training doesn't stop despite reaching num_train_epochs 

### ISSUE THREAD

**Issue by parthpatwa** [SivilTaram/Persona-Dialogue-Generation#11]
in train_transmitter.py:
num_train_epochs = 4
Despite that the model keeps training after 4 epochs. 
pfa
![transmitter](https://user-images.githubusercontent.com/30171629/92222721-0e0a3100-eebd-11ea-8b2a-31d396c5718a.png)

**Comment by SivilTaram** [comment]
@parthpatwa It does not occur for me in my experiments. However, you could just shut down it and find the latest checkpoint as Transmitter model.

**Comment by parthpatwa** [comment]
I think I found why is it happening:
1) in train_transmitter.py line 74: num_train_epochs = 4
2) however in parlai/scripts/train_model.py line 237:   self.max_num_epochs = opt['num_epochs'] if opt['num_epochs'] > 0 else float('inf')

so parlai expects the key to be 'num_epochs' not 'num_train_epochs'

is this correct reason?
If yes, should I go ahead and open a Pull Request?

**Comment by SivilTaram** [comment]
@parthpatwa Yeah, you catch it. I will be very happy if you could open a PR 👍

**Comment by parthpatwa** [comment]
@SivilTaram done, check.

**Comment by parthpatwa** [comment]
@SivilTaram ignore the num_epoch PR. I will open a new one.

**Comment by SivilTaram** [comment]
@parthpatwa Thanks :)
