### ISSUE TITLE
File not found and other errors

### ISSUE THREAD

**Issue by warriorKnightStar** [SivilTaram/Persona-Dialogue-Generation#19]
When I ran this : 
python train_transmitter.py 
 it ended with the following :  
![train_transmitter](https://user-images.githubusercontent.com/74771222/100107718-f7f28800-2e8f-11eb-8f5b-184443f78d07.png)

After the above , I went ahead and executed : 
python tasks/convai2receiver/build_data.py

and encountered the following:
![parl_filenotfound](https://user-images.githubusercontent.com/74771222/100108122-74856680-2e90-11eb-9bb1-ee089962f5ae.png)

Please help!

**Comment by SivilTaram** [comment]
@warriorKnightStar could you check if there is any folder named as `data/ConvAI2`? If YES and you are using linux systems, you could replace `\\` in `tasks/convai2receiver/build_data.py` with '/' and try again.

**Comment by warriorKnightStar** [comment]
Yes there is a folder `data/ConvAI2` and I'm using windows. Please could I know how to resolve the problem in the first pic attached which was the result after running : python train_transmitter.py 

Please help

**Comment by SivilTaram** [comment]
@warriorKnightStar It seems normal for training on transmitter. If you does not use `ctrl` + `c` to stop it, it will keep running and training. So what's the problem here?

**Comment by warriorKnightStar** [comment]
I did not press `ctrl` + `c` to stop it.. I did not press or click anything to interrupt its execution... but it stopped. I'm not sure if it should run for more epochs . Please could you look at the last 5 lines in the output pic  and confirm if that's the way the correct execution ends or is something wrong on my side?

**Comment by SivilTaram** [comment]
@warriorKnightStar As far as I know, ^C usually means that you killed the process by yourself, or maybe the special case for codalab? You could try again with a smaller batch size and replace `10` with a smaller number [here](https://github.com/SivilTaram/Persona-Dialogue-Generation/blob/3cc800ffe3c5a8d16ed26522cda839acfab8d417/train_transmitter.py#L39). Try again and see if the process will be killed by colab.

**Comment by SivilTaram** [comment]
If you have further questions, please reopen it.
