### ISSUE TITLE
RuntimeError: invalid argument 4: Index tensor must have same dimensions as input tensor at /pytorch/aten/src/THC/generic/THCTensorScatterGather.cu:16

### ISSUE THREAD

**Issue by leyi-123** [SivilTaram/Persona-Dialogue-Generation#20]
Hi!  When I ran "python train_transmitter.py", I had the following problem:
![error](https://user-images.githubusercontent.com/62412393/100242463-c6e98480-2f6f-11eb-8605-ffed781cc64e.png)
Configuration: python 3.7.9, pytorch 1.0.1, torchvision 0.5.0
Set up the environment according to the instructions you gave.
Thanks for your help!

**Comment by SivilTaram** [comment]
@leyi-123 It's wired. Could you print the values of `pos_seq_len_expand` here?

**Comment by leyi-123** [comment]
> 
> 
> @leyi-123 It's wired. Could you print the values of `pos_seq_len_expand` here?

Sorry I could't understand what "pos_seq_len_expand" means. If it refers to the error, it will be shown as follows :
Traceback (most recent call last):
  File "train_transmitter.py", line 145, in <module>
    TrainLoop(opt).train()
  File "/home1/zhenli/Persona-Dialogue-Generation/parlai/scripts/train_model.py", line 512, in train
    world.parley()
  File "/home1/zhenli/Persona-Dialogue-Generation/parlai/core/worlds.py", line 663, in parley
    batch_act = self.batch_act(agent_idx, batch_observations[agent_idx])
  File "/home1/zhenli/Persona-Dialogue-Generation/parlai/core/worlds.py", line 636, in batch_act
    batch_actions = a.batch_act(batch_observation)
  File "/home1/zhenli/Persona-Dialogue-Generation/agents/transmitter/transmitter.py", line 858, in batch_act
    self.init_cuda_buffer(batchsize)
  File "/home1/zhenli/Persona-Dialogue-Generation/agents/transmitter/transmitter.py", line 854, in init_cuda_buffer
    raise e
  File "/home1/zhenli/Persona-Dialogue-Generation/agents/transmitter/transmitter.py", line 843, in init_cuda_buffer
    sc = self.model(input_dummy, None, None, output_dummy, None)[1]
  File "/home1/zhenli/anaconda3/envs/p2bot/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home1/zhenli/Persona-Dialogue-Generation/agents/transmitter/gpt/model.py", line 99, in forward
    last_state = hidden_states.gather(dim=1, index=pos_seq_len_expand).squeeze(dim=1)
RuntimeError: invalid argument 4: Index tensor must have same dimensions as input tensor at /pytorch/aten/src/THC/generic/THCTensorScatterGather.cu:16

**Comment by SivilTaram** [comment]
@leyi-123 find the 99th line in `Persona-Dialogue-Generation/agents/transmitter/gpt/model.py`, and print the value of the size of `pos_seq_len_expand` and `hidden_states` as:
```python
print(hidden_states.shape)
print(pos_seq_len_expand.shape)
```
And post the log here.

**Comment by leyi-123** [comment]
> 
> 
> @leyi-123 find the 99th line in `Persona-Dialogue-Generation/agents/transmitter/gpt/model.py`, and print the value of the size of `pos_seq_len_expand` and `hidden_states` as:
> 
> ```python
> print(hidden_states.size())
> print(pos_seq_len_expand.size())
> ```
> 
> And post the log here.

hidden_states.size():
torch.Size([102, 40516])
pos_seq_len_expand.size():
torch.Size([2, 1, 768])

**Comment by SivilTaram** [comment]
@leyi-123 Could you check again if you have **uninstalled** the official `transformers` lib and **installed** the custom one from https://github.com/SivilTaram/transformers.git ? The size of `hidden_states` in my environment is as `torch.Size([2, 258, 768])`.

**Comment by leyi-123** [comment]
> 
> 
> @leyi-123 Could you check again if you have **uninstalled** the official `transformers` lib and **installed** the custom one from https://github.com/SivilTaram/transformers.git ? The size of `hidden_states` in my environment is as `torch.Size([10, 258, 768])` in default setting.

It's working! Thank you very much!

**Comment by SivilTaram** [comment]
@leyi-123 Glad to hear that!
