### ISSUE TITLE
你好，我们在开发一个AI恋人产品，想和你交流一下。

### ISSUE THREAD

**Issue by 1973sir** [SivilTaram/Persona-Dialogue-Generation#24]
你好，我们是一个初创团队，目前在开发一个AI恋人的项目，内部测试地址：http://ailover.tpddns.cn:8088/predict/
想请问你是否对我们的项目感兴趣，想和你交流一下。
请加我的微信：
![image](https://user-images.githubusercontent.com/1441981/108823634-a925cd00-75fb-11eb-941b-9f55c8901d4a.png)
谢谢！

**Comment by SivilTaram** [comment]
@1973sir If you have any question or problem, please contact me via my email (`qian dot liu at buaa dot edu dot cn`), thanks.
