### ISSUE TITLE
Errors when run  train_psquare.py 

### ISSUE THREAD

**Issue by xhc19930714** [SivilTaram/Persona-Dialogue-Generation#27]
![image](https://user-images.githubusercontent.com/17611259/114720673-cc066f00-9d6a-11eb-9458-316b142329c0.png) It indicates that token indice is longer than the specified maximum sequence length for GPT(512). Where should I fix this problem? my GPU is 2 rtx3090.  Probably large enough to run your model?

**Comment by SivilTaram** [comment]
@xhc19930714 Sorry for the late response. The error means that your input sequence should be pruned into 512 tokens (the maximum length which GPT2 can acccept), or you may turn into other models to find a better one.

I suggest pruning your data to aovid too long sequence.

**Comment by Guaguago** [comment]
"UnboundLocalError: local variable 'language_opt' referenced before assignment"

Hi, I met this problem when running the train_psquare.py,  how to fix it? thanks

**Comment by SivilTaram** [comment]
Closed since there is no more activity.
