### ISSUE TITLE
selfplay dialogue

### ISSUE THREAD

**Issue by artyomche9** [SivilTaram/Persona-Dialogue-Generation#29]
Maybe the problem is me, but I can't rewrite interactive.py so that it works in selfplay mode. Could you please publish a script that generates the selfplay dialog as in the first image in the repository readme?

**Comment by SivilTaram** [comment]
@artyomche9 Thanks for your interest on our work! Do you mean that you want to have two agents self-play in inference? Or for training purpose?

**Comment by artyomche9** [comment]
@SivilTaram Thank you for your reply. I would like the script to return a dialog of two agents with different predicates (in the script interactive.py they are stored in the bot_persona variable).

**Comment by SivilTaram** [comment]
@artyomche9 I see. It will cost nearly 1~2 weeks to do it for me since I'm rushing a coming deadline. If there is any update, I will mention you here, and please stay tuned! BTW, PRs are warmly welcome!

**Comment by artyomche9** [comment]
@SivilTaram Good afternoon, have you made any progress?

**Comment by SivilTaram** [comment]
@artyomche9 Sorry for the late response, and YES, there is progress. But I did not complete it as expected. Since I have an urgent deadline, I'd like to complete the script before July 10. Thank you in advance for your patience.

**Comment by SivilTaram** [comment]
@artyomche9 Hello! Sorry for the delay. After struggling for a few days, I fail to finish a similar interface as in `interactive.py` to initialize two agents and let them talk to each other. If you wanna to observe how two agents talk to each other in training, I would recommend you to train the model with *zero* learning rate, and display examples frequently.

**Comment by artyomche9** [comment]
Thank you for help
