### ISSUE TITLE
Can not find receiver_revised.model

### ISSUE THREAD

**Issue by cbj0535** [SivilTaram/Persona-Dialogue-Generation#30]
When I run train_receiver.py, it can not find "receiver_revised.model in tmp/receiver/".  Is it normal to run "train_receiver.py" to generate "receiver_revised. Model"? Or do I have to download it in advance and put it in this corresponding path?

**Comment by SivilTaram** [comment]
If I remermber correctly, it is normal to run "train_receiver.py" to generate "receiver_revised.model".

**Comment by SivilTaram** [comment]
Please feel free to reopen the issue there is any question.
