### ISSUE TITLE
"Learning rate multiplier set to 0.0."  when training the transmitter.

### ISSUE THREAD

**Issue by Guaguago** [SivilTaram/Persona-Dialogue-Generation#31]
Hello, a very interesting paper 
I get the following message very frequently through the training transmitter process.  
"Training beyond specified ‘t_total’. Learning rate multiplier set to 0.0. Please set ‘t_total’ of WarmupLinearSchedule correctly." 
Did u meet the same messages before? 
Is there anything wrong?

**Comment by SivilTaram** [comment]
I didn't meet the same message before. Could you share the full log here pls?

**Comment by SivilTaram** [comment]
Closed since there is no more activity.

**Comment by Cool-tong** [comment]
![warning](https://user-images.githubusercontent.com/57522472/134840036-fe035081-2ad9-43aa-a1a5-e89c5bd52845.png)

**Comment by Cool-tong** [comment]
I ran into the same problem.

**Comment by Choitsugun** [comment]
I ran into the same problem.

**Comment by SivilTaram** [comment]
@Choitsugun Could you confirm if the version of dependency, especially as described [here](https://github.com/SivilTaram/Persona-Dialogue-Generation#install-custom-dependencies) is correct? Thanks!
