### ISSUE TITLE
Error running train_psquare.py

### ISSUE THREAD

**Issue by VishruthR** [SivilTaram/Persona-Dialogue-Generation#33]
When I try to run train_psquare.py I get: 'UnboundLocalError: local variable 'language_opt' referenced before assignment. The specific line this error occurs at is line 416 on psquare.py. I think this error is due to the fact that in psquare.py it looks for a file named 'transmitter_revised.model' in the 'tmp/transmitter' directory but in this directory, I only have 'transmitter_revised.model.dict.opt' and 'transmitter_revised.model.dict'. Is there any solution to this problem?

**Comment by SivilTaram** [comment]
@VishruthR Could you kindly check the installation of decencies?
