### ISSUE TITLE
RuntimeError: Error(s) in loading state_dict for Gpt2SeqModel:

### ISSUE THREAD

**Issue by bott1eee** [SivilTaram/Persona-Dialogue-Generation#34]
Hello! When i ran "python train_transmitter.py", i had encountered the following problems:

> Traceback (most recent call last):
  File "train_transmitter.py", line 145, in <module>
    TrainLoop(opt).train()
  File "/Persona-Dialogue-Generation-master/parlai/scripts/train_model.py", line 228, in __init__
    self.agent = create_agent(opt)
  File "/Persona-Dialogue-Generation-master/parlai/core/agents.py", line 547, in create_agent
    model = load_agent_module(opt)
  File "/Persona-Dialogue-Generation-master/parlai/core/agents.py", line 424, in load_agent_module
    return model_class(new_opt)
  File "/Persona-Dialogue-Generation-master/agents/transmitter/transmitter.py", line 408, in __init__
    self.model.load_state_dict(states['model'])
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 830, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for Gpt2SeqModel:
	Unexpected key(s) in state_dict: "transformer_module.transformer.tokens_embed.weight", "transformer_module.transformer.positions_embed.weight", "transformer_module.transformer.h.0.attn.bias", "transformer_module.transformer.h.0.attn.c_attn.weight", "transformer_module.transformer.h.0.attn.c_attn.bias", "transformer_module.transformer.h.0.attn.c_proj.weight", "transformer_module.transformer.h.0.attn.c_proj.bias", "transformer_module.transformer.h.0.ln_1.weight", "transformer_module.transformer.h.0.ln_1.bias", "transformer_module.transformer.h.0.mlp.c_fc.weight", "transformer_module.transformer.h.0.mlp.c_fc.bias", "transformer_module.transformer.h.0.mlp.c_proj.weight", "transformer_module.transformer.h.0.mlp.c_proj.bias", "transformer_module.transformer.h.0.ln_2.weight", "transformer_module.transformer.h.0.ln_2.bias", "transformer_module.transformer.h.1.attn.bias", "transformer_module.transformer.h.1.attn.c_attn.weight", "transformer_module.transformer.h.1.attn.c_attn.bias", "transformer_module.transformer.h.1.attn.c_proj.weight", "transformer_module.transformer.h.1.attn.c_proj.bias", "transformer_module.transformer.h.1.ln_1.weight", "transformer_module.transformer.h.1.ln_1.bias", "transformer_module.transformer.h.1.mlp.c_fc.weight", "transformer_module.transformer.h.1.mlp.c_fc.bias", "transformer_module.transformer.h.1.mlp.c_proj.weight", "transformer_module.transformer.h.1.mlp.c_proj.bias", "transformer_module.transformer.h.1.ln_2.weight", "transformer_module.transformer.h.1.ln_2.bias", "transformer_module.transformer.h.2.attn.bias", "transformer_module.transformer.h.2.attn.c_attn.weight", "transformer_module.transformer.h.2.attn.c_attn.bias", "transformer_module.transformer.h.2.attn.c_proj.weight", "transformer_module.transformer.h.2.attn.c_proj.bias", "transformer_module.transformer.h.2.ln_1.weight", "transformer_module.transformer.h.2.ln_1.bias", "transformer_module.transformer.h.2.mlp.c_fc.weight", "transformer_module.transformer.h.2.mlp.c_fc.bias", "transformer_module.transformer.h.2.mlp.c_proj.weight", "transformer_module.transformer.h.2.mlp.c_proj.bias", "transformer_module.transformer.h.2.ln_2.weight", "transformer_module.transformer.h.2.ln_2.bias", "transformer_module.transformer.h.3.attn.bias", "transformer_module.transformer.h.3.attn.c_attn.weight", "transformer_module.transformer.h.3.attn.c_attn.bias", "transformer_module.transformer.h.3.attn.c_proj.weight", "transformer_module.transformer.h.3.attn.c_proj.bias", "transformer_module.transformer.h.3.ln_1.weight", "transformer_module.transformer.h.3.ln_1.bias", "transformer_module.transformer.h.3.mlp.c_fc.weight", "transformer_module.transformer.h.3.mlp.c_fc.bias", "transformer_module.transformer.h.3.mlp.c_proj.weight", "transformer_module.transformer.h.3.mlp.c_proj.bias", "transformer_module.transformer.h.3.ln_2.weight", "transformer_module.transformer.h.3.ln_2.bias", "transformer_module.transformer.h.4.attn.bias", "transformer_module.transformer.h.4.attn.c_attn.weight", "transformer_module.transformer.h.4.attn.c_attn.bias", "transformer_module.transformer.h.4.attn.c_proj.weight", "transformer_module.transformer.h.4.attn.c_proj.bias", "transformer_module.transformer.h.4.ln_1.weight", "transformer_module.transformer.h.4.ln_1.bias", "transformer_module.transformer.h.4.mlp.c_fc.weight", "transformer_module.transformer.h.4.mlp.c_fc.bias", "transformer_module.transformer.h.4.mlp.c_proj.weight", "transformer_module.transformer.h.4.mlp.c_proj.bias", "transformer_module.transformer.h.4.ln_2.weight", "transformer_module.transformer.h.4.ln_2.bias", "transformer_module.transformer.h.5.attn.bias", "transformer_module.transformer.h.5.attn.c_attn.weight", "transformer_module.transformer.h.5.attn.c_attn.bias", "transformer_module.transformer.h.5.attn.c_proj.weight", "transformer_module.transformer.h.5.attn.c_proj.bias", "transformer_module.transformer.h.5.ln_1.weight", "transformer_module.transformer.h.5.ln_1.bias", "transformer_module.transformer.h.5.mlp.c_fc.weight", "transformer_module.transformer.h.5.mlp.c_fc.bias", "transformer_module.transformer.h.5.mlp.c_proj.weight", "transformer_module.transformer.h.5.mlp.c_proj.bias", "transformer_module.transformer.h.5.ln_2.weight", "transformer_module.transformer.h.5.ln_2.bias", "transformer_module.transformer.h.6.attn.bias", "transformer_module.transformer.h.6.attn.c_attn.weight", "transformer_module.transformer.h.6.attn.c_attn.bias", "transformer_module.transformer.h.6.attn.c_proj.weight", "transformer_module.transformer.h.6.attn.c_proj.bias", "transformer_module.transformer.h.6.ln_1.weight", "transformer_module.transformer.h.6.ln_1.bias", "transformer_module.transformer.h.6.mlp.c_fc.weight", "transformer_module.transformer.h.6.mlp.c_fc.bias", "transformer_module.transformer.h.6.mlp.c_proj.weight", "transformer_module.transformer.h.6.mlp.c_proj.bias", "transformer_module.transformer.h.6.ln_2.weight", "transformer_module.transformer.h.6.ln_2.bias", "transformer_module.transformer.h.7.attn.bias", "transformer_module.transformer.h.7.attn.c_attn.weight", "transformer_module.transformer.h.7.attn.c_attn.bias", "transformer_module.transformer.h.7.attn.c_proj.weight", "transformer_module.transformer.h.7.attn.c_proj.bias", "transformer_module.transformer.h.7.ln_1.weight", "transformer_module.transformer.h.7.ln_1.bias", "transformer_module.transformer.h.7.mlp.c_fc.weight", "transformer_module.transformer.h.7.mlp.c_fc.bias", "transformer_module.transformer.h.7.mlp.c_proj.weight", "transformer_module.transformer.h.7.mlp.c_proj.bias", "transformer_module.transformer.h.7.ln_2.weight", "transformer_module.transformer.h.7.ln_2.bias", "transformer_module.transformer.h.8.attn.bias", "transformer_module.transformer.h.8.attn.c_attn.weight", "transformer_module.transformer.h.8.attn.c_attn.bias", "transformer_module.transformer.h.8.attn.c_proj.weight", "transformer_module.transformer.h.8.attn.c_proj.bias", "transformer_module.transformer.h.8.ln_1.weight", "transformer_module.transformer.h.8.ln_1.bias", "transformer_module.transformer.h.8.mlp.c_fc.weight", "transformer_module.transformer.h.8.mlp.c_fc.bias", "transformer_module.transformer.h.8.mlp.c_proj.weight", "transformer_module.transformer.h.8.mlp.c_proj.bias", "transformer_module.transformer.h.8.ln_2.weight", "transformer_module.transformer.h.8.ln_2.bias", "transformer_module.transformer.h.9.attn.bias", "transformer_module.transformer.h.9.attn.c_attn.weight", "transformer_module.transformer.h.9.attn.c_attn.bias", "transformer_module.transformer.h.9.attn.c_proj.weight", "transformer_module.transformer.h.9.attn.c_proj.bias", "transformer_module.transformer.h.9.ln_1.weight", "transformer_module.transformer.h.9.ln_1.bias", "transformer_module.transformer.h.9.mlp.c_fc.weight", "transformer_module.transformer.h.9.mlp.c_fc.bias", "transformer_module.transformer.h.9.mlp.c_proj.weight", "transformer_module.transformer.h.9.mlp.c_proj.bias", "transformer_module.transformer.h.9.ln_2.weight", "transformer_module.transformer.h.9.ln_2.bias", "transformer_module.transformer.h.10.attn.bias", "transformer_module.transformer.h.10.attn.c_attn.weight", "transformer_module.transformer.h.10.attn.c_attn.bias", "transformer_module.transformer.h.10.attn.c_proj.weight", "transformer_module.transformer.h.10.attn.c_proj.bias", "transformer_module.transformer.h.10.ln_1.weight", "transformer_module.transformer.h.10.ln_1.bias", "transformer_module.transformer.h.10.mlp.c_fc.weight", "transformer_module.transformer.h.10.mlp.c_fc.bias", "transformer_module.transformer.h.10.mlp.c_proj.weight", "transformer_module.transformer.h.10.mlp.c_proj.bias", "transformer_module.transformer.h.10.ln_2.weight", "transformer_module.transformer.h.10.ln_2.bias", "transformer_module.transformer.h.11.attn.bias", "transformer_module.transformer.h.11.attn.c_attn.weight", "transformer_module.transformer.h.11.attn.c_attn.bias", "transformer_module.transformer.h.11.attn.c_proj.weight", "transformer_module.transformer.h.11.attn.c_proj.bias", "transformer_module.transformer.h.11.ln_1.weight", "transformer_module.transformer.h.11.ln_1.bias", "transformer_module.transformer.h.11.mlp.c_fc.weight", "transformer_module.transformer.h.11.mlp.c_fc.bias", "transformer_module.transformer.h.11.mlp.c_proj.weight", "transformer_module.transformer.h.11.mlp.c_proj.bias", "transformer_module.transformer.h.11.ln_2.weight", "transformer_module.transformer.h.11.ln_2.bias", "transformer_module.lm_head.decoder.weight". 

What can I do to solve this problem? thanks!

**Comment by SivilTaram** [comment]
@bott1eee Have you installed the correct lib according to the README?
