### ISSUE TITLE
build_data.py ERROR

### ISSUE THREAD

**Issue by Libincn-HNU** [SivilTaram/Persona-Dialogue-Generation#6]
Hi, when i run the python tasks/convai2receiver/build_data.py
after it downloads the data, later it doesn't work 
i change the maincode:
if __name__ == '__main__':
    build_data("./data/ConvAI2/train_both_original.txt")
    build_data("./data/ConvAI2/valid_both_original.txt")
    build_data("./data/ConvAI2/train_both_revised.txt")
    build_data("./data/ConvAI2/valid_both_revised.txt")
it seems there is some --dict-file parameter i should set? error as below: 
**Tried to build dictionary but `--dict-file` is not set.** 
Set this param so the dictionary can be saved.
how can i set this parameter to fix it ? and keep it running.

**Comment by SivilTaram** [comment]
@Libincn-HNU This is a warning (not an error), so you could ignore it.

 You could try to run `python train_receiver_model.py`. If it not succeed, please report the log here. In theory,  it will be okay with or without dict-file.

One more word, the reason why we do not need a dict-file anymore is that we employ BERT, which requires a pre-built BERT vocabulary.

**Comment by Libincn-HNU** [comment]
Thx，now it works!
